# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portfolio
email: daboramidu93@gmail.com
description: >-
  Results-driven Software & AI/ML Engineer with 3+ years of experience building intelligent, scalable, and ethical software solutions in generative AI, data science, cloud computing, and backend development. I specialize in tools like Python, R, HTML, CSS, JavaScript, TensorFlow, Hugging Face, LangChain, Azure, AWS, Modal, Weights & Biases, and Gradio to deliver real-world impact and innovation.
github_username: Amidu-Dabor
minimal_mistakes_skin: air # Professional, clean theme with strong typography
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages
  - assets/files
  - search.json
  - search.html

exclude:
  - _posts

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Amidu Dabor"
  avatar : "/assets/images/Amidu_Dabor_Passport_Photo_2.jpg"
  bio    : "Software & AI/ML Engineer | Data Scientist | Creative Writer"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/adabor/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Amidu-Dabor"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:daboramidu93@gmail.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/adabor/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Amidu-Dabor"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:daboramidu93@gmail.com"

defaults:
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
